name: ci 
on:
  push:
    branches:
      - master
  pull_request:
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created 

jobs:
  analysis:
    name: static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          path: go/src/github.com/kafkaesque-io/burnell

      - name: Lint Go Code
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
          go get -u golang.org/x/lint/golint 
          cd src
          golint ./...

  build_test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          path: go/src/github.com/kafkaesque-io/burnell
      - name: Build Binary
        run: |
          go mod download
          cd src
          go build ./...
      - name: Go Vet
        run: |
          cd src
          go vet ./...
      - name: Go unit test
        run : |
          cd src/unit-test
          go test
      - name: Pulsar token validation
        run : |
          ls /tmp
          sudo docker run -v /tmp:/tmp apachepulsar/pulsar:2.6.1 bin/pulsar tokens create --secret-key /tmp/unitest-keypair-private.key --subject test-user
          sudo docker run -v /tmp:/tmp apachepulsar/pulsar:2.6.1 bin/pulsar tokens show -f /tmp/myadmin.jwt
          sudo docker run -v /tmp:/tmp apachepulsar/pulsar:2.6.1 bin/pulsar tokens validate -pk /tmp/unitest-keypair-public.key -f /tmp/myadmin.jwt | grep '{sub=myadmin}'
  docker:
    name: docker
    runs-on: ubuntu-latest 
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          path: go/src/github.com/kafkaesque-io/burnell

      - name: Build Burnell Docker Image
        run: |
          pwd
          sudo docker build -t burnell .
      - name: Build Burnell Logcollector Docker Image
        run: |
          pwd
          sudo docker build -t burnell-logcollector -f ./dockerfiles/logserver/Dockerfile .